### PR TITLE
Pls accept

### PR DESCRIPTION
**Pull request by Supremolink81**
Yay

### CODE REVIEW

**Comment by Supremolink81** [comment]
My intro is awesome

**Comment by eleanortien** [comment]
You're the guy from the CS Discord! :o

**Comment by Supremolink81** [comment]
How do you know who I am? :O

**Comment by eleanortien** [comment]
You are like a celeb on there. :)

**Comment by Supremolink81** [comment]
Then who are you on there...?

**Comment by eleanortien** [comment]
CrescentMoon (leafeon profile picture), I haven't said much on the discord yet.

**Comment by Supremolink81** [comment]
Where are you in this room? 0_0

**Comment by eleanortien** [comment]
Front left, short person in a grey shirt.

**Pull request merged**
